export interface CryptoFormModel {
    currency:       string;
    cryptoCurrency: string;
}

// Generated by https://quicktype.io

export interface CryptoCurrency {
    Message:       string;
    Type:          number;
    MetaData:      MetaData;
    SponsoredData: any[];
    Data:          Datum[];
    RateLimit:     RateLimit;
    HasWarning:    boolean;
}

export interface Datum {
    CoinInfo: CoinInfo;
    RAW:      Raw;
    DISPLAY:  Display;
}

export interface CoinInfo {
    Id:                 string;
    Name:               string;
    FullName:           string;
    Internal:           string;
    ImageUrl:           string;
    Url:                string;
    Algorithm:          string;
    ProofType:          string;
    Rating:             Rating;
    NetHashesPerSecond: number;
    BlockNumber:        number;
    BlockTime:          number;
    BlockReward:        number;
    AssetLaunchDate:    string;
    MaxSupply:          number;
    Type:               number;
    DocumentType:       DocumentType;
}

export enum DocumentType {
    Webpagecoinp = "Webpagecoinp",
}

export interface Rating {
    Weiss: Weiss;
}

export interface Weiss {
    Rating:                   string;
    TechnologyAdoptionRating: string;
    MarketPerformanceRating:  string;
}

export interface Display {
    USD: { [key: string]: string };
}

export interface Raw {
    USD: Usd;
}

export interface Usd {
    TYPE:                    string;
    MARKET:                  Market;
    FROMSYMBOL:              string;
    TOSYMBOL:                Tosymbol;
    FLAGS:                   string;
    PRICE:                   number;
    LASTUPDATE:              number;
    MEDIAN:                  number;
    LASTVOLUME:              number;
    LASTVOLUMETO:            number;
    LASTTRADEID:             string;
    VOLUMEDAY:               number;
    VOLUMEDAYTO:             number;
    VOLUME24HOUR:            number;
    VOLUME24HOURTO:          number;
    OPENDAY:                 number;
    HIGHDAY:                 number;
    LOWDAY:                  number;
    OPEN24HOUR:              number;
    HIGH24HOUR:              number;
    LOW24HOUR:               number;
    LASTMARKET:              string;
    VOLUMEHOUR:              number;
    VOLUMEHOURTO:            number;
    OPENHOUR:                number;
    HIGHHOUR:                number;
    LOWHOUR:                 number;
    TOPTIERVOLUME24HOUR:     number;
    TOPTIERVOLUME24HOURTO:   number;
    CHANGE24HOUR:            number;
    CHANGEPCT24HOUR:         number;
    CHANGEDAY:               number;
    CHANGEPCTDAY:            number;
    CHANGEHOUR:              number;
    CHANGEPCTHOUR:           number;
    CONVERSIONTYPE:          Conversiontype;
    CONVERSIONSYMBOL:        string;
    SUPPLY:                  number;
    MKTCAP:                  number;
    MKTCAPPENALTY:           number;
    CIRCULATINGSUPPLY:       number;
    CIRCULATINGSUPPLYMKTCAP: number;
    TOTALVOLUME24H:          number;
    TOTALVOLUME24HTO:        number;
    TOTALTOPTIERVOLUME24H:   number;
    TOTALTOPTIERVOLUME24HTO: number;
    IMAGEURL:                string;
}

export enum Conversiontype {
    Direct = "direct",
}

export enum Market {
    Cccagg = "CCCAGG",
}

export enum Tosymbol {
    Usd = "USD",
}

export interface MetaData {
    Count: number;
}

export interface RateLimit {
}


// Generated by https://quicktype.io

export interface CryptoExchange {
    RAW:     RawExchange;
    DISPLAY: DisplayExchange;
}

export interface DisplayExchange {
    DisplayCryptoExchange: DisplayCryptoExchange;
}

export interface DisplayCryptoExchange {
    Currency: { [key: string]: string };
}

export interface RawExchange {
    CurrencyCtypto: RawCryptoExchange;
}

export interface RawCryptoExchange {
    CurrencyExchange: CurrencyExchange;
}

export interface CurrencyExchange {
    TYPE:                    string;
    MARKET:                  string;
    FROMSYMBOL:              string;
    TOSYMBOL:                string;
    FLAGS:                   string;
    PRICE:                   number;
    LASTUPDATE:              number;
    MEDIAN:                  number;
    LASTVOLUME:              number;
    LASTVOLUMETO:            number;
    LASTTRADEID:             string;
    VOLUMEDAY:               number;
    VOLUMEDAYTO:             number;
    VOLUME24HOUR:            number;
    VOLUME24HOURTO:          number;
    OPENDAY:                 number;
    HIGHDAY:                 number;
    LOWDAY:                  number;
    OPEN24HOUR:              number;
    HIGH24HOUR:              number;
    LOW24HOUR:               number;
    LASTMARKET:              string;
    VOLUMEHOUR:              number;
    VOLUMEHOURTO:            number;
    OPENHOUR:                number;
    HIGHHOUR:                number;
    LOWHOUR:                 number;
    TOPTIERVOLUME24HOUR:     number;
    TOPTIERVOLUME24HOURTO:   number;
    CHANGE24HOUR:            number;
    CHANGEPCT24HOUR:         number;
    CHANGEDAY:               number;
    CHANGEPCTDAY:            number;
    CHANGEHOUR:              number;
    CHANGEPCTHOUR:           number;
    CONVERSIONTYPE:          string;
    CONVERSIONSYMBOL:        string;
    SUPPLY:                  number;
    MKTCAP:                  number;
    MKTCAPPENALTY:           number;
    CIRCULATINGSUPPLY:       number;
    CIRCULATINGSUPPLYMKTCAP: number;
    TOTALVOLUME24H:          number;
    TOTALVOLUME24HTO:        number;
    TOTALTOPTIERVOLUME24H:   number;
    TOTALTOPTIERVOLUME24HTO: number;
    IMAGEURL:                string;
}
